// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzQk7J2HlttT1DPSkFjBlEsttgbNtGsgw',
    appId: '1:232116512315:web:43661a55ea044c24081e1e',
    messagingSenderId: '232116512315',
    projectId: 'ticket-gest',
    authDomain: 'ticket-gest.firebaseapp.com',
    storageBucket: 'ticket-gest.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDDrq3qy-RvXTXFrKnXYXomqN2uD4DPrs',
    appId: '1:232116512315:android:a3acb2a8f212b0f5081e1e',
    messagingSenderId: '232116512315',
    projectId: 'ticket-gest',
    storageBucket: 'ticket-gest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkA05BSQ4CMSEQTO6YRT0ID7ghVGYEDcQ',
    appId: '1:232116512315:ios:7330344fd6c8f557081e1e',
    messagingSenderId: '232116512315',
    projectId: 'ticket-gest',
    storageBucket: 'ticket-gest.appspot.com',
    iosBundleId: 'com.example.gestionTicketFlutter',
  );

}